#!/bin/bash

notebook_paths=`git diff --cached --name-only --diff-filter=d | grep  .ipynb`

if [ ! -z "$notebook_paths" ]
then
    for path in $notebook_paths
    do
        jupyter nbconvert --to html $path
        jupyter nbconvert --clear-output --inplace $path
        git add ${path/.ipynb/.html}
        git add $path
    done
fi