#!/bin/bash

set -eu

if ! command -v jupyter nbconvert -h &> /dev/null
then
    echo "************************************** WARNING **************************************"
    echo "*        The companion HTML version won't be created or updated automatically       *"
    echo "*        Run 'pip install ipython~=5.10.0 nbconvert~=5.6.1' to fix this             *"
    echo "*************************************************************************************"
else
    notebook_paths=`git diff --cached --name-only --diff-filter=d | grep  .ipynb; echo ""`

    if [ ! -z "$notebook_paths" ]
    then
        for path in $notebook_paths
        do
            jupyter nbconvert --to html $path
            jupyter nbconvert --clear-output --inplace $path
            git add ${path/.ipynb/.html}
            git add $path
        done
    fi
fi