#!/bin/bash

set -eu

if ! command -v jupyter &> /dev/null
then
    echo "ERROR: Cannot find 'jupyter' on your path so the HTML version won't be created/updated automatically"
    echo "ERROR: Install 'jupyter' from https://docs.jupyter.org/en/latest/install.html to fix this"
    exit(1)
elif ! command -v jq &> /dev/null
then
    echo "ERROR: Cannot find 'jq' on your path so the HTML version won't be created/updated automatically"
    echo "ERROR: Install 'jq' from https://stedolan.github.io/jq/download/ to fix this"
    exit(1)
else
    notebook_paths=`git diff --cached --name-only --diff-filter=d | grep  .ipynb; echo ""`

    if [ ! -z "$notebook_paths" ]
    then
        for path in $notebook_paths
        do
            # Remove widget states which would fail nbconvert
            cat <<< `jq 'del(.metadata.widgets)' $path` > $path

            jupyter nbconvert --to html $path
            jupyter nbconvert --clear-output --inplace $path
            git add ${path/.ipynb/.html}
            git add $path
        done
    fi
fi