name: build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  main:

    runs-on: macos-10.15
    strategy:
      matrix:
        part: [
          introductory/Part_2_*.ipynb,
          introductory/Part_3_*.ipynb,
          introductory/Part_4_*.ipynb,
          introductory/Part_5_*.ipynb
        ]

    steps:
      - uses: actions/checkout@v2
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.7"
      - name: Install dependencies
        run: |
          pip install -U pip
          pip install -r requirements.txt
      - name: Run tutorial
        run: |
          pytest --collect-only --nbmake ./notebooks/${{ matrix.part }}
          pytest --nbmake --nbmake-timeout=1800 ./notebooks/${{ matrix.part }}
